---
version: 2
jobs:
  node-12:
    docker:
      - image: node:12
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run: git config user.email 'circleci@ci.local'
      - run: git config user.name 'CircleCI'
      - run:
          name: Install dependencies
          command: yarn
      - run: ./bin/run --version
      - run: ./bin/run --help
      - run: $(npm bin)/changeset version
      - run: yarn pack
      - run:
          name: Testing
          command: yarn test
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - add_ssh_keys:
          fingerprints:
            - '07:b2:80:43:fe:a6:08:d1:72:cb:64:5d:ba:b6:b5:7c'
      - run:
          name: Publish
          command: $(npm bin)/changeset publish
      - run: git push --follow-tags
  cache:
    docker:
      - image: node:12
    working_directory: ~/cli
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  '@ryaninvents/changeset-run':
    jobs:
      - node-12:
          context: gh-npm-public
      - cache:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
